import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import warnings
from .drop import DropPath
import sys
import numpy as np

import torch.distributed as dist

class AvgMeter:
    def __init__(self, N=1000000):
        self.N = N
        self.data = []
        self.sum = 0

    def update(self, x):
        self.data.append(x)
        self.sum += x

        if len(self.data) > self.N:
            self.sum -= self.data[0]
            self.data = self.data[1:]
    
    def avg(self):
        if len(self.data) == 0: return -1
        return self.sum / len(self.data)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def zero_module(module):
    """
    Zero out the parameters of a module and return it.
    """
    for p in module.parameters():
        p.detach().zero_()
    return module

def timestep_embedding(timesteps, dim, max_period=10000):
    """
    Create sinusoidal timestep embeddings.
    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional.
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
    half = dim // 2
    freqs = torch.exp(
        -math.log(max_period) * torch.arange(start=0, end=half, dtype=torch.float32) / half
    ).to(device=timesteps.device)
    args = timesteps[:, None].float() * freqs[None]
    embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
    if dim % 2:
        embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
    return embedding


### U-MAE loss ###
def UMAE_loss(features):
    '''
    features: [N, C]
    '''
    features = F.normalize(features, eps=1e-5)
    sim = features @ features.T 
    loss = sim.pow(2).mean()

    if torch.any(torch.isnan(loss)):
        print('#'*50 + '\nError! UMAE_loss is nan. Set loss to zero.\n' + '#'*50)
        return 0.

    return loss

def token_uniformity_loss(features, mean_feature=None, normalize=True):
    '''
    features: [N, L, C]
    '''
    if mean_feature is not None:
        features = features - mean_feature
    if normalize:
        features = F.normalize(features, dim=-1)
    sim = features @ features.permute(0, 2, 1)
    loss = sim.pow(2).mean()

    if torch.any(torch.isnan(loss)):
        print('#'*50 + '\nError! token_uniformity_loss is nan. Set loss to zero.\n' + '#'*50)
        return 0.
    
    return loss

def get_MinSNR_weights(diffusion, gamma=5):
    SNR = diffusion.alphas_cumprod / (1.0 - diffusion.alphas_cumprod + 1e-3)
    weights = gamma / SNR
    weights[weights > 1.] = 1.
    weights = torch.Tensor(weights)
    weights = weights * len(weights) / weights.sum()
    return weights

def get_MaxSNR_weights(diffusion, gamma=5):
    SNR = diffusion.alphas_cumprod / (1.0 - diffusion.alphas_cumprod + 1e-3)
    weights = gamma / SNR
    weights[weights < 1.] = 1.
    weights = torch.Tensor(weights) * len(weights) / weights.sum()
    return weights

def remove_zero_data(x, x_aug):

    with torch.no_grad():

        N, C, T, V, M = x.shape
        new_x, new_x_aug = [], []

        baseline = x[...,0].abs().mean()

        for i in range(N):
            new_x.append(x[i:i+1,:,:,:,0:1])
            new_x_aug.append(x_aug[i:i+1,:,:,:,0:1])

            if (x[i,:,:,:,1].abs().mean(dim=[0,2]) < 1e-5).float().mean() > 0.2: continue 

            new_x.append(x[i:i+1,:,:,:,1:])
            new_x_aug.append(x_aug[i:i+1,:,:,:,1:])

            if len(new_x) >= N: break
            
        new_x = torch.cat(new_x, dim=0)#[:N] # avg length: 28/24
        new_x_aug = torch.cat(new_x_aug, dim=0)#[:N]

    return new_x, new_x_aug







